---
- name: install tomcat server
  hosts: webserver
  become: true
  tasks:
    - name: Install Java openjdk-11-jdk
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: create tomcat group
      ansible.builtin.group:
        name: "{{ group }}"
        state: present

      

        
