---
- name: install tomcat server
  hosts: webserver
  become: true
  tasks:
    - name: Install Java
      ansible.builtin.apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present

      

        
