---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-pod
spec:
  minReadySeconds: 5
  replicas: 5
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      name: jenkins-pod
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts-jdk17
          ports:
            - containerPort: 8080
        - name: alpine
          image: alpine:3.20
          args: 
            - sleep
            - 1d


          
     
  