---
- name: install game of life
  hosts: all
  become: true
  vars: 
    java_package: 
      - openjdk-8-jdk
      - tomcat9
    tomcat_package: tomcat9
    tomcat_path: /var/lib/tomcat9/wapapps/gameoflife.war
    source_path: https://referenceapplicationskhaja.s3.us-west-2.amazonaws.com/gameoflife.war
  tasks:
    - name: install java
      ansible.builtin.apt:
        name: "{{  java_package }}"
        update_cache: yes
        state: present
    - name: download war file
      ansible.builtin.get_url:
        url: "{{ source_path }}"
        dest: "{{ tomcat_path }}"
      notify:
        - restart tomcat9
  handlers:
    - name: restart tomcat9
      ansible.builtin.service:
        name: tomcat9
        state: restarted
