---
packages:
  - dotnet-sdk-8.0
  - unzip
source_path: https://github.com/nopSolutions/nopCommerce/releases/download/release-4.70.1/nopCommerce_4.70.1_NoSource_linux_x64.zip
dest_path: /tmp/nopCommerce_4.70.1_NoSource_linux_x64.zip
nop_path: /nop
bin: /nop/bin
logs: /nop/logs
