---
- name: install lamp server in radhat
  hosts: RedHat
  vars:
    info_page_path: /var/www/html/info.php
  become: true
  tasks:
    - name: install httpd server
      ansible.builtin.package:
        name: "{{ package_name }}"
        state: present
    - name: enable and start httpd
      ansible.builtin.systemd:
        name: "{{ package_name }}"
        enabled: yes
        state: started
    - name: install httpd php server
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
        loop: "{{ php_packages }}"
      notify: 
        - restart apache
    - name: copy php info.php
      ansible.builtin.copy:
        src: info.php
        dest: "{{ info_page_path }}"
      notify: 
        - restart apache
  handlers:
    - name: restart apache
      ansible.builtin.systemd:
        name: "{{ package_name }}"
        state: restarted