---
- name: install lamp server in radhat
  hosts: all
  become: true
  vars:
    info_php_path: /var/www/html/info.php
  tasks:
    - name: install apache server
      ansible.builtin.package:
        name: "{{ package_name }}"
        state: present
    - name: enable and start apache
      ansible.builtin.systemd:
        name: "{{ package_name }}"
        enabled: yes
        state: started
    - name: install php
      ansible.builtin.yum:
        name:
          - php
        state: present
      when: ansible_facts['os_family'] == 'RedHat'
      notify: 
        - restart apache
    - name: copy info php
      ansible.builtin.copy:
        src: info.php
        dest: "{{ info_php_path }}"
      notify: 
        - restart apache
    - name: install php
      ansible.builtin.apt:
        name:
          - php
          - libapache2-mod-php
        state: present
      when: ansible_facts['os_family'] == 'Ubuntu'
  handlers:
    - name: restart apache
      ansible.builtin.service:
        name: "{{ package_name }}"
        state: restarted