---
- name: install lamp server in radhat
  hosts: ubuntu
  become: true
  tasks:
    - name: install apache server
      yum:
        name: httpd
        state: present
    - name: enable and start apache
      ansible.builtin.systemd:
        name: httpd
        enabled: yes
        state: started
    - name: install php
      yum:
        name:
          - php
        state: present
      notify: 
        - restart apache
    - name: copy info php
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php
      notify: 
        - restart apache
    - name: apache install
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present
      notify: 
        - restart apache2
    - name: install php
      ansible.builtin.apt:
        name:
          - php
          - libapache2-mod-php
        state: present
    - name: copy php info.php
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php
      notify: 
        - restart apache2
  handlers:
    - name: restart apache
      ansible.builtin.service:
        name: httpd
        state: restarted
    - name: restart apache2
      ansible.builtin.service:
        name: apache2
        state: restarted