---
- name: install lamp server in radhat
  hosts: webserver
  become: true
  vars:
    info_php_path: /var/www/html/info.php
  tasks:
    - name: massage if this playbook being executed 
      ansible.builtin.fail: 
        msg: this playbook is designed to run for Ubuntu and RedHat
      when: ansible_facts['distribution'] != "Ubuntu" and ansible_facts['distribution'] != "RedHat"
    - name: install httpd
      ansible.builtin.package:
        name: "{{ package_name }}"
        state: present
    - name: enable and start apache
      ansible.builtin.systemd:
        name: "{{ package_name }}"
        enabled: yes
        state: started
    - name: install php
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ php_packages }}"
      notify: 
        - restart apache
    - name: copy info php
      ansible.builtin.copy:
        src: info.php
        dest: "{{ info_php_path }}"
      notify:
        - restart apache
  handlers:
    - name: restart apache
      ansible.builtin.service:
        name: "{{ package_name }}"
        state: restarted