---
- name: install lamp server in radhat
  hosts: webserver
  become: true
  vars:
    info_php_path: /var/www/html/info.php
  tasks:
    - name: check if the playbook is being executed on supported OS
      ansible.builtin.fail: 
        msg: this playbook is designed to run for Ubuntu and RedHat
      when: ansible_facts['distribution'] != "Ubuntu" and ansible_facts['distribution'] != "RedHat"
    - name: install httpd
      ansible.builtin.package:
        name: "{{ package_name }}"
        state: present
    - name: debug apache installed
      ansible.builtin.debug:
        msg: "installed apache server using {{ package_name }}"
        verbosity: 1
    - name: enable and start apache
      ansible.builtin.systemd:
        name: "{{ package_name }}"
        enabled: yes
        state: started
    - name: debug apache services
      ansible.builtin.debug:
        msg: "Enabled and started apache services"
        verbosity: 1
    - name: install php
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ php_packages }}"
      notify: 
        - restart apache
    - name: debug php installed
      ansible.builtin.debug:
        msg: "installed php package using {{ php_packages }}"
        verbosity: 1
    - name: copy info php
      ansible.builtin.copy:
        src: info.php
        dest: "{{ info_php_path }}"
      notify:
        - restart apache
    - name: debug create path
      ansible.builtin.debug:
        msg: "created info at {{ info_php_path }}"
        verbosity: 1
  handlers:
    - name: restart apache
      ansible.builtin.service:
        name: "{{ package_name }}"
        state: restarted