---
- name: install tomcat server
  hosts: webserver
  vars:
    java_package: openjdk-11-jdk
    group: tomcat
    user: tomcat
    homedir: /opt/tomcat
    shell: /bin/false
    tomcat_major_version: 10
    tomcat_version: 10.1.26
  become: true
  tasks:
    - name: Install Java
      ansible.builtin.apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
    - name: create tomcat group
      ansible.builtin.group:
        name: "{{ group }}"
        state: present
    - name: create tomcate user
      ansible.builtin.user:
        name: "{{ user }}"
        group: "{{ group }}"
        create_home: yes
        home: "{{ homedir }}"
        shell: "{{ shell }}"
        state: present
    - name: download tomcat
      ansible.builtin.get_url:
        url: "https://www-eu.apache.org/dist/tomcat/tomcat-{{ tomcat_major_version }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
    - name: extract tomcat tar file
      ansible.builtin.unarchive:
        src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ homedir }}"
        remote_src: yes
        owner: "{{ user }}"
        group: "{{ group }}"
        creates: "{{ homedir }}/apache-tomcat-{{ tomcat_version }}"
      

        
