apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-sv
  labels:
    app: nginx
spec:
  minReadySeconds: 5
  replicas: 6
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      name: nginx-sv
      labels:
        app: nginx-pod
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80